name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  course_advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']
    +persist_docs:
      relation: true
      columns: true
    
    # hiding models within the staging subfolder
    bingeflix:
      staging:
        +materialized: view
        +docs:
          node_color: "#023020"
    
    staging:
      +schema: staging
    
    intermediate:
      +schema: intermediate

    marts:
      core:
        materialized: table
        +schema: core_reporting
        +docs:
          node_color: "green"
      finance:
        +schema: finance
      product:
        +schema: product
  
  dbt_project_evaluator:
    marts:
      tests:
      +enabled: false
    dag:
      fct_model_fanout:
        +enabled: false

  # hiding a dbt package
  dbt_artifacts:
    +docs:
      show: false
seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

vars:
  exclude_packages: ["/models/legacy/"] # excludes a specific package

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
